"""add futuristic theme fields

Revision ID: 66ae1d41a9b9
Revises: 9132b19a2758
Create Date: 2026-03-11 21:34:18.992041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ae1d41a9b9'
down_revision = '9132b19a2758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heading_text', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('fluid_color_1', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('fluid_color_2', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('fluid_color_3', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('badge_bg', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('badge_text', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('badge_border', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_column('badge_border')
        batch_op.drop_column('badge_text')
        batch_op.drop_column('badge_bg')
        batch_op.drop_column('fluid_color_3')
        batch_op.drop_column('fluid_color_2')
        batch_op.drop_column('fluid_color_1')
        batch_op.drop_column('heading_text')

    # ### end Alembic commands ###
