"""fresh init from current models

Revision ID: 9132b19a2758
Revises: 
Create Date: 2026-03-11 21:15:29.778320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9132b19a2758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('native_name', sa.String(length=80), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_code'), ['code'], unique=True)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_in_menu', sa.Boolean(), nullable=False),
    sa.Column('menu_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_is_in_menu'), ['is_in_menu'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_slug'), ['slug'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('group', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)

    op.create_table('security_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp_mode', sa.String(length=16), nullable=False),
    sa.Column('otp_mode_admin', sa.String(length=16), nullable=True),
    sa.Column('otp_mode_student', sa.String(length=16), nullable=True),
    sa.Column('otp_mode_staff', sa.String(length=16), nullable=True),
    sa.Column('otp_ttl_minutes', sa.Integer(), nullable=False),
    sa.Column('otp_max_sends_per_hour', sa.Integer(), nullable=False),
    sa.Column('otp_max_verify_attempts', sa.Integer(), nullable=False),
    sa.Column('failed_login_threshold', sa.Integer(), nullable=False),
    sa.Column('lockout_minutes', sa.Integer(), nullable=False),
    sa.Column('suspicious_window_days', sa.Integer(), nullable=False),
    sa.Column('trust_device_days', sa.Integer(), nullable=False),
    sa.Column('api_rate_limit', sa.String(length=64), nullable=False),
    sa.Column('ai_rate_limit', sa.String(length=64), nullable=False),
    sa.Column('max_upload_mb', sa.Integer(), nullable=False),
    sa.Column('allowed_upload_extensions', sa.String(length=255), nullable=False),
    sa.Column('csp_report_only', sa.Boolean(), nullable=False),
    sa.Column('csp_report_uri', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=True),
    sa.Column('default_meta_title', sa.String(length=255), nullable=True),
    sa.Column('default_meta_description', sa.String(length=500), nullable=True),
    sa.Column('default_og_image', sa.String(length=500), nullable=True),
    sa.Column('google_site_verification', sa.String(length=255), nullable=True),
    sa.Column('bing_site_verification', sa.String(length=255), nullable=True),
    sa.Column('ga4_measurement_id', sa.String(length=64), nullable=True),
    sa.Column('gtm_container_id', sa.String(length=64), nullable=True),
    sa.Column('head_html', sa.Text(), nullable=True),
    sa.Column('body_start_html', sa.Text(), nullable=True),
    sa.Column('body_end_html', sa.Text(), nullable=True),
    sa.Column('robots_policy', sa.String(length=32), nullable=True),
    sa.Column('extra_robots_lines', sa.Text(), nullable=True),
    sa.Column('sitemap_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=32), nullable=True),
    sa.Column('whatsapp_message', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('bg', sa.String(length=32), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=True),
    sa.Column('surface_2', sa.String(length=32), nullable=True),
    sa.Column('border', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('muted', sa.String(length=64), nullable=True),
    sa.Column('primary', sa.String(length=32), nullable=True),
    sa.Column('shadow', sa.String(length=128), nullable=True),
    sa.Column('radius', sa.String(length=16), nullable=True),
    sa.Column('input_bg', sa.String(length=64), nullable=True),
    sa.Column('input_border', sa.String(length=64), nullable=True),
    sa.Column('css_overrides', sa.Text(), nullable=True),
    sa.Column('background_mode', sa.String(length=24), nullable=True),
    sa.Column('background_image_url', sa.String(length=512), nullable=True),
    sa.Column('gradient_start', sa.String(length=32), nullable=True),
    sa.Column('gradient_end', sa.String(length=32), nullable=True),
    sa.Column('parallax_enabled', sa.Boolean(), nullable=True),
    sa.Column('fluid_enabled', sa.Boolean(), nullable=True),
    sa.Column('noise_overlay_enabled', sa.Boolean(), nullable=True),
    sa.Column('glass_level', sa.String(length=24), nullable=True),
    sa.Column('glow_intensity', sa.Integer(), nullable=True),
    sa.Column('blur_strength', sa.Integer(), nullable=True),
    sa.Column('hover_style', sa.String(length=24), nullable=True),
    sa.Column('motion_level', sa.String(length=24), nullable=True),
    sa.Column('icon_style', sa.String(length=32), nullable=True),
    sa.Column('icon_glow', sa.Boolean(), nullable=True),
    sa.Column('button_shape', sa.String(length=24), nullable=True),
    sa.Column('button_radius', sa.String(length=16), nullable=True),
    sa.Column('card_style', sa.String(length=32), nullable=True),
    sa.Column('table_style', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_themes_is_active'), ['is_active'], unique=False)

    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('src_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('context', sa.String(length=120), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_translation_cache_context'), ['context'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_cache_src_lang'), ['src_lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_cache_target_lang'), ['target_lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_cache_version'), ['version'], unique=False)

    op.create_table('page_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('sections_json', sa.Text(), nullable=True),
    sa.Column('faq_json', sa.Text(), nullable=True),
    sa.Column('links_json', sa.Text(), nullable=True),
    sa.Column('hero_title', sa.String(length=255), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=120), nullable=True),
    sa.Column('hero_cta_url', sa.String(length=255), nullable=True),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('twitter_card', sa.String(length=40), nullable=True),
    sa.Column('json_ld', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'lang_code', name='uq_page_contents_page_lang')
    )
    with op.batch_alter_table('page_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_contents_lang_code'), ['lang_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_contents_page_id'), ['page_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('target_exam', sa.String(length=40), nullable=True),
    sa.Column('current_level', sa.String(length=40), nullable=True),
    sa.Column('target_score', sa.String(length=40), nullable=True),
    sa.Column('native_language', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('study_goal', sa.Text(), nullable=True),
    sa.Column('preferred_study_time', sa.String(length=40), nullable=True),
    sa.Column('profile_completed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('admin_permission_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_admin_perm_override')
    )
    with op.batch_alter_table('admin_permission_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_permission_overrides_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_permission_overrides_user_id'), ['user_id'], unique=False)

    op.create_table('api_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_call_logs_actor_user_id'), ['actor_user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('track_type', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_is_premium'), ['is_premium'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_owner_admin_id'), ['owner_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_track_type'), ['track_type'], unique=False)

    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_hash', sa.String(length=128), nullable=True),
    sa.Column('device_type', sa.String(length=40), nullable=True),
    sa.Column('browser', sa.String(length=120), nullable=True),
    sa.Column('os_name', sa.String(length=120), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_device_hash'), ['device_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('link_path', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('otp_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('sent_to', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('device_hash', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts_left', sa.Integer(), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_device_hash'), ['device_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_user_id'), ['user_id'], unique=False)

    op.create_table('pronunciation_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('ipa_summary', sa.Text(), nullable=True),
    sa.Column('accent_notes', sa.Text(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pronunciation_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pronunciation_profiles_student_id'), ['student_id'], unique=True)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ui_language_code', sa.String(length=20), nullable=False),
    sa.Column('learning_language_code', sa.String(length=20), nullable=False),
    sa.Column('accent', sa.String(length=20), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('browser_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('autoplay_voice', sa.Boolean(), nullable=False),
    sa.Column('playback_speed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_security_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('last_device_hash', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_security_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_security_states_locked_until'), ['locked_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_security_states_user_id'), ['user_id'], unique=True)

    op.create_table('certificate_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_code', sa.String(length=80), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_code')
    )
    with op.batch_alter_table('certificate_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_records_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_records_student_id'), ['student_id'], unique=False)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usage_limit_total', sa.Integer(), nullable=True),
    sa.Column('usage_limit_per_user', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('first_purchase_only', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_coupons_course_id'), ['course_id'], unique=False)

    op.create_table('course_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('subtitle', sa.String(length=120), nullable=True),
    sa.Column('template_key', sa.String(length=40), nullable=False),
    sa.Column('animation_key', sa.String(length=40), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_on_frontpage', sa.Boolean(), nullable=False),
    sa.Column('show_on_dashboard', sa.Boolean(), nullable=False),
    sa.Column('show_on_library', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_badges_course_id'), ['course_id'], unique=True)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['enrolled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollments_student_course')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_enrolled_by_id'), ['enrolled_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('learning_analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('speaking_accuracy', sa.Float(), nullable=False),
    sa.Column('practice_minutes', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_analytics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_analytics_snapshots_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_analytics_snapshots_student_id'), ['student_id'], unique=False)

    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_levels_course_id'), ['course_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=True),
    sa.Column('lesson_type', sa.String(length=40), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('explanation_tts_text', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_lesson_type'), ['lesson_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_slug'), ['slug'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=128), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=128), nullable=True),
    sa.Column('gateway_signature', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_gateway_order_id'), ['gateway_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_gateway_payment_id'), ['gateway_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_user_id'), ['user_id'], unique=False)

    op.create_table('subsections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('grammar_formula', sa.String(length=180), nullable=True),
    sa.Column('grammar_tags', sa.String(length=500), nullable=True),
    sa.Column('hint_seed', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subsections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subsections_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('subsection_id', sa.Integer(), nullable=True),
    sa.Column('completed_questions', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subsection_id'], ['subsections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_lesson_progress_student_lesson')
    )
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_progress_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_subsection_id'), ['subsection_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('hint_text', sa.Text(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('evaluation_rubric', sa.Text(), nullable=True),
    sa.Column('expected_keywords', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subsection_id'], ['subsections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_prompt_type'), ['prompt_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subsection_id'), ['subsection_id'], unique=False)

    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('subsection_id', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('stt_transcript', sa.Text(), nullable=True),
    sa.Column('response_mode', sa.String(length=30), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('ai_detected_grammar', sa.String(length=180), nullable=True),
    sa.Column('is_correctish', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subsection_id'], ['subsections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_attempts_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_response_mode'), ['response_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_subsection_id'), ['subsection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempts_subsection_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_response_mode'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_chapter_id'))

    op.drop_table('question_attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_subsection_id'))
        batch_op.drop_index(batch_op.f('ix_questions_prompt_type'))
        batch_op.drop_index(batch_op.f('ix_questions_language_code'))
        batch_op.drop_index(batch_op.f('ix_questions_is_active'))

    op.drop_table('questions')
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_progress_subsection_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_chapter_id'))

    op.drop_table('lesson_progress')
    with op.batch_alter_table('subsections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subsections_chapter_id'))

    op.drop_table('subsections')
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_payment_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_course_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_coupon_id'))

    op.drop_table('coupon_redemptions')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_lesson_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_gateway_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_gateway_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_course_id'))
        batch_op.drop_index(batch_op.f('ix_payments_coupon_id'))

    op.drop_table('payments')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_slug'))
        batch_op.drop_index(batch_op.f('ix_lessons_level_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_lesson_type'))
        batch_op.drop_index(batch_op.f('ix_lessons_is_published'))

    op.drop_table('lessons')
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_levels_course_id'))

    op.drop_table('levels')
    with op.batch_alter_table('learning_analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_analytics_snapshots_student_id'))
        batch_op.drop_index(batch_op.f('ix_learning_analytics_snapshots_course_id'))

    op.drop_table('learning_analytics_snapshots')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_enrollments_enrolled_by_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('course_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_badges_course_id'))

    op.drop_table('course_badges')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_course_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_code'))

    op.drop_table('coupons')
    with op.batch_alter_table('certificate_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_records_course_id'))

    op.drop_table('certificate_records')
    with op.batch_alter_table('user_security_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_security_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_security_states_locked_until'))

    op.drop_table('user_security_states')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('pronunciation_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pronunciation_profiles_student_id'))

    op.drop_table('pronunciation_profiles')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_user_id'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_expires_at'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_device_hash'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_created_at'))

    op.drop_table('otp_challenges')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_events_success'))
        batch_op.drop_index(batch_op.f('ix_login_events_device_hash'))
        batch_op.drop_index(batch_op.f('ix_login_events_created_at'))

    op.drop_table('login_events')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_track_type'))
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_slug'))
        batch_op.drop_index(batch_op.f('ix_courses_owner_admin_id'))
        batch_op.drop_index(batch_op.f('ix_courses_language_code'))
        batch_op.drop_index(batch_op.f('ix_courses_is_published'))
        batch_op.drop_index(batch_op.f('ix_courses_is_premium'))
        batch_op.drop_index(batch_op.f('ix_courses_difficulty'))
        batch_op.drop_index(batch_op.f('ix_courses_created_by_id'))

    op.drop_table('courses')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_call_logs_actor_user_id'))

    op.drop_table('api_call_logs')
    with op.batch_alter_table('admin_permission_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_permission_overrides_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_permission_overrides_permission_id'))

    op.drop_table('admin_permission_overrides')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_admin_id'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('page_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_contents_page_id'))
        batch_op.drop_index(batch_op.f('ix_page_contents_lang_code'))

    op.drop_table('page_contents')
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_version'))
        batch_op.drop_index(batch_op.f('ix_translation_cache_target_lang'))
        batch_op.drop_index(batch_op.f('ix_translation_cache_src_lang'))
        batch_op.drop_index(batch_op.f('ix_translation_cache_context'))
        batch_op.drop_index(batch_op.f('ix_translation_cache_cache_key'))

    op.drop_table('translation_cache')
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_themes_is_active'))

    op.drop_table('themes')
    op.drop_table('seo_settings')
    op.drop_table('security_policies')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_pages_is_published'))
        batch_op.drop_index(batch_op.f('ix_pages_is_in_menu'))

    op.drop_table('pages')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_code'))

    op.drop_table('languages')
    # ### end Alembic commands ###
