from __future__ import annotations


def theme_to_builder_payload(theme) -> dict:
    return {
        "name": getattr(theme, "name", ""),
        "primary": getattr(theme, "primary", "#0d6efd"),
        "bg": getattr(theme, "bg", "#06111f"),
        "surface": getattr(theme, "surface", "#0b1a2c"),
        "surface_2": getattr(theme, "surface_2", "#0f2238"),
        "text": getattr(theme, "text", "rgba(255,255,255,.92)"),
        "muted": getattr(theme, "muted", "rgba(255,255,255,.62)"),
        "border": getattr(theme, "border", "rgba(255,255,255,.08)"),
        "radius": getattr(theme, "radius", "16px"),
        "shadow": getattr(theme, "shadow", "0 12px 30px rgba(0,0,0,.45)"),
        "input_bg": getattr(theme, "input_bg", "rgba(255,255,255,.04)"),
        "input_border": getattr(theme, "input_border", "rgba(255,255,255,.10)"),
        "css_overrides": getattr(theme, "css_overrides", "") or "",
        "font_family": getattr(theme, "font_family", "Segoe UI, Arial, Helvetica, sans-serif"),
        "heading_font_family": getattr(theme, "heading_font_family", getattr(theme, "font_family", "Bahnschrift, Segoe UI, Arial, Helvetica, sans-serif")),
        "accent_font_family": getattr(theme, "accent_font_family", "Consolas, Cascadia Mono, SFMono-Regular, Menlo, monospace"),
        "background_mode": getattr(theme, "background_mode", "solid"),
        "background_image_url": getattr(theme, "background_image_url", ""),
        "gradient_start": getattr(theme, "gradient_start", getattr(theme, "bg", "#06111f")),
        "gradient_end": getattr(theme, "gradient_end", getattr(theme, "surface_2", "#0f2238")),
        "parallax_enabled": getattr(theme, "parallax_enabled", False),
        "fluid_enabled": getattr(theme, "fluid_enabled", False),
        "noise_overlay_enabled": getattr(theme, "noise_overlay_enabled", False),
        "alphabet_background_enabled": getattr(theme, "alphabet_background_enabled", False),
        "alphabet_trails_enabled": getattr(theme, "alphabet_trails_enabled", True),
        "alphabet_rotation_depth": getattr(theme, "alphabet_rotation_depth", 60),
        "alphabet_speed": getattr(theme, "alphabet_speed", 100),
        "alphabet_min_size": getattr(theme, "alphabet_min_size", 18),
        "alphabet_max_size": getattr(theme, "alphabet_max_size", 66),
        "alphabet_count": getattr(theme, "alphabet_count", 64),
        "alphabet_motion_mode": getattr(theme, "alphabet_motion_mode", "float"),
        "alphabet_direction_x": getattr(theme, "alphabet_direction_x", 0),
        "alphabet_direction_y": getattr(theme, "alphabet_direction_y", 100),
        "alphabet_opacity": getattr(theme, "alphabet_opacity", 82),
        "alphabet_trail_length": getattr(theme, "alphabet_trail_length", 14),
        "alphabet_tilt_x": getattr(theme, "alphabet_tilt_x", 18),
        "alphabet_tilt_y": getattr(theme, "alphabet_tilt_y", 12),
        "alphabet_tilt_z": getattr(theme, "alphabet_tilt_z", 30),
        "alphabet_outline_only": getattr(theme, "alphabet_outline_only", False),
        "alphabet_outline_color": getattr(theme, "alphabet_outline_color", "#ffffff"),
        "header_sticky_enabled": getattr(theme, "header_sticky_enabled", False),
        "header_transparent_enabled": getattr(theme, "header_transparent_enabled", False),
        "glass_level": getattr(theme, "glass_level", "off"),
        "glow_intensity": getattr(theme, "glow_intensity", 0),
        "blur_strength": getattr(theme, "blur_strength", 0),
        "hover_style": getattr(theme, "hover_style", "subtle"),
        "motion_level": getattr(theme, "motion_level", "normal"),
        "icon_style": getattr(theme, "icon_style", "bootstrap"),
        "icon_glow": getattr(theme, "icon_glow", False),
        "button_shape": getattr(theme, "button_shape", "rounded"),
        "button_radius": getattr(theme, "button_radius", "12px"),
        "card_style": getattr(theme, "card_style", "glass-dark"),
        "table_style": getattr(theme, "table_style", "dark-modern"),
        "heading_text": getattr(theme, "heading_text", getattr(theme, "text", "rgba(255,255,255,.92)")),
        "workspace_kicker_text": getattr(theme, "workspace_kicker_text", getattr(theme, "muted", "rgba(255,255,255,.62)")),
        "workspace_kicker_size": getattr(theme, "workspace_kicker_size", ".75rem"),
        "workspace_kicker_weight": getattr(theme, "workspace_kicker_weight", "700"),
        "page_title_size": getattr(theme, "page_title_size", "2rem"),
        "page_title_weight": getattr(theme, "page_title_weight", "800"),
        "page_title_transform": getattr(theme, "page_title_transform", "none"),
        "page_title_spacing": getattr(theme, "page_title_spacing", "0"),
        "badge_bg": getattr(theme, "badge_bg", "rgba(255,255,255,.08)"),
        "badge_text": getattr(theme, "badge_text", "#ffffff"),
        "badge_border": getattr(theme, "badge_border", "rgba(255,255,255,.12)"),
        "fluid_color_1": getattr(theme, "fluid_color_1", "#00b7ff"),
        "fluid_color_2": getattr(theme, "fluid_color_2", "#7c3aed"),
        "fluid_color_3": getattr(theme, "fluid_color_3", "#00f5d4"),
    }


def apply_builder_payload_to_theme(theme, payload: dict):
    simple_fields = [
        "name",
        "primary",
        "bg",
        "surface",
        "surface_2",
        "text",
        "muted",
        "border",
        "radius",
        "shadow",
        "input_bg",
        "input_border",
        "css_overrides",
        "font_family",
        "heading_font_family",
        "accent_font_family",
    ]

    future_fields = [
        "background_mode",
        "background_image_url",
        "gradient_start",
        "gradient_end",
        "parallax_enabled",
        "fluid_enabled",
        "noise_overlay_enabled",
        "alphabet_background_enabled",
        "alphabet_trails_enabled",
        "alphabet_rotation_depth",
        "alphabet_speed",
        "alphabet_min_size",
        "alphabet_max_size",
        "alphabet_count",
        "alphabet_motion_mode",
        "alphabet_direction_x",
        "alphabet_direction_y",
        "alphabet_opacity",
        "alphabet_trail_length",
        "alphabet_tilt_x",
        "alphabet_tilt_y",
        "alphabet_tilt_z",
        "alphabet_outline_only",
        "alphabet_outline_color",
        "header_sticky_enabled",
        "header_transparent_enabled",
        "glass_level",
        "glow_intensity",
        "blur_strength",
        "hover_style",
        "motion_level",
        "icon_style",
        "icon_glow",
        "button_shape",
        "button_radius",
        "card_style",
        "table_style",
        "heading_text",
        "workspace_kicker_text",
        "workspace_kicker_size",
        "workspace_kicker_weight",
        "page_title_size",
        "page_title_weight",
        "page_title_transform",
        "page_title_spacing",
        "badge_bg",
        "badge_text",
        "badge_border",
        "fluid_color_1",
        "fluid_color_2",
        "fluid_color_3",
    ]

    for key in simple_fields:
        if key in payload and hasattr(theme, key):
            setattr(theme, key, payload[key])

    for key in future_fields:
        if key in payload and hasattr(theme, key):
            setattr(theme, key, payload[key])

    return theme
